In [1]:
import numpy as np

In [8]:
A = np.array([[1,2],[4,5]])

B = np.array([[1,2],[3,4]])

C = np.array([[11,12],[14,15]])

In [ ]:
# se multiplica matriz por matriz pero solo de dos dimensiones vectore unidimensionales
D = np.dot(A,B)
print(D)    

[[ 7 10]
 [19 28]]


In [10]:
E = A @ B
print(E)

[[ 7 10]
 [19 28]]


In [12]:
#calcular el determinante de una matriz
np. linalg.det(D)

np.float64(6.000000000000001)

In [13]:
print (D)

[[ 7 10]
 [19 28]]


In [15]:
#Calcular la inversa de una matriz si su determinante es distinto de 0 entonces se puede calcular la inversa
det_A = np.linalg.det(B)
if det_A != 0:
    inv_A = np.linalg.inv(B)
    print("Inversa de la matriz: \n", inv_A)
else:
    print("La matriz no es invertible")

Inversa de la matriz: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
M= np.array([[3,3],[3,3]])

In [20]:
det_M = np.linalg.det(M)
print(M)
if det_M != 0:
    inv_M = np.linalg.inv(M)
    print("Inversa de la matriz: \n",inv_M)
else:
    print("La matriz no es invertible")

[[3 3]
 [3 3]]
La matriz no es invertible


In [ ]:
# DESCOMPOSICIÓN DE MATRICES, factorizado en una octagonal y una triangular inferior
Q , R = np.linalg.qr(A)


In [23]:
print("Factor Q:\n",Q)
print("Factor R:\n",R)

Factor Q:
 [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
Factor R:
 [[-4.12310563 -5.33578375]
 [ 0.         -0.72760688]]


In [25]:
Q @ R

array([[1., 2.],
       [4., 5.]])