In [4]:
import numpy as np # 

In [5]:
L =[1,2,3,4,5,6,7,8,9,10]

In [6]:
A = np.array(L)

In [7]:
print(L)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
L[1]

2

In [11]:
L2 = [[1,2],[3,4]]
A2 = np.array(L2)


In [12]:
print (L2)
print (A2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [14]:
#arraYS  de ceros y unos
zeros_array = np.zeros((2,3)) # el 2 es la cantidad de filas y el 3 la cantidad de columnas
ones_array = np.ones((3,2))
print("Zeros_array: \n", zeros_array)
print("Ones_array: \n", ones_array)

Zeros_array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones_array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
