In [1]:
import numpy as np

In [14]:
a =np.array([1,2,3,4,5,6,7,8,9,50])

b = np.array([11,12,13,14,15,16,17,18,19,20])

In [ ]:
#suma
#por este medio se puede agregar un argumento 
np.add(a,b) 

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 70])

In [ ]:
#por este medio se puede agregar un argumento  , para definir el tipo de dato que se quiere que el resultado tenga, parametros adicionales
w=np.add(a,b,dtype= np.int32)

In [25]:
type(w[0])

numpy.int32

In [ ]:

#Resta
np.subtract(a,b)

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [ ]:
#multiplicacion
np.multiply(a,b)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [ ]:
#division
np.divide(a,b)

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [11]:
angles = np.array([0,30,60,90,120,150,180,210,240,270,300,330])
angles_rad = np.radians(angles)

def cos(angle):
    return np.cos(angle)

def sin(angle):
    return np.sin(angle)

def tan(angle):
    return np.tan(angle)

def acos(angle):
    return np.arccos(angle)

def asin(angle):
    return np.arcsin(angle)

def atan(angle):
    return np.arctan(angle)

def atan2(y,x):
    return np.arctan2(y,x)

def cosh(angle):
    return np.cosh(angle)

def sinh(angle):
    return np.sinh(angle)

def tanh(angle):
    return np.tanh(angle)

def acosh(angle):
    return np.arccosh(angle)

def asinh(angle):
    return np.arcsinh(angle)

def atanh(angle):
    return np.arctanh(angle)    

In [12]:
np.tan(angles_rad)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16,  5.77350269e-01,
        1.73205081e+00,  5.44374645e+15, -1.73205081e+00, -5.77350269e-01])

In [13]:
np.greater(a,b)

array([False, False, False, False, False, False, False, False, False,
       False])

In [15]:
np.sin(angles)

array([ 0.        , -0.98803162, -0.30481062,  0.89399666,  0.58061118,
       -0.71487643, -0.80115264,  0.46771852,  0.94544515, -0.17604595,
       -0.99975584, -0.13238163])

In [16]:
np.equal(a,b)

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
#Elevar el valor de una lista
np.power(a,b)

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       5474894590040342528])

In [ ]:
#promedio de la lista
np.mean(a)


np.float64(9.5)

In [21]:
#desviacion estandar
np.std(a)

np.float64(13.720422734012244)