In [33]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a[5]

np.int64(6)

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print (b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b[-1,-1]

np.int64(8)

In [13]:
#arange
c = np.arange(122)
print(c)

#arange

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121]


In [15]:
c[::7]

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119])

In [17]:
d = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12],[13,14,15,16]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
#subrtraes sub arrays
d[:2, :2]


array([[1, 2],
       [5, 6]])

In [19]:
# extraer los valores :: significa que trae la primera y 1 2 y asi de dos en dos
d[:, ::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [21]:
 #indexacion 
e=np.array([1,2,3,4,5,6,7,8,9,10])
indices=np.array([0,2,4,6,-1])

e[indices]

array([ 1,  3,  5,  7, 10])

In [34]:
#indexacion booleana

f =np.array([1,-1,-2,3,-3,3,-4,4])



In [35]:
print(f)

[ 1 -1 -2  3 -3  3 -4  4]


In [36]:
condition = f >0
condition

array([ True, False, False,  True, False,  True, False,  True])

In [38]:
f[condition]

array([1, 3, 3, 4])