In [2]:
import numpy as np

In [ ]:
#x= va a hacer una copia de z con copy
# si se necesita crear una independiente de z
#ventajas de copiar , desventajas de copiar utilizar espacio en memoria
z=np.array([2,3,4])
x = z.copy()
z[1]=9

In [10]:
print('x: ',x)
print('z: ',z)

x:  [2 3 4]
z:  [2 9 4]


In [ ]:
a = np.arange (1,10)
print (a)
#cambiar la forma, lo que hace el 3,3 es multiplicarlo por el valor de la diagonal, pero si digamos tengo 10, elementos como este ejemplo solo puede ser hasta 9
b=a.reshape(3,3)
print (b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#crea una copia de un array
c = b.flatten() 
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:

d = b.ravel () 
print(d)

In [19]:
# se cambia vista,  debido a la forma aplanada y tambien se cambia la forma matricial
# consume menos memoria
d[0] = 99

In [18]:
b

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
b.transpose()

array([[99,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [ ]:
# b. T ,lo que realiza el transpose de la matriz
b.T

array([[99,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [22]:
np.min(b)

np.int64(2)

In [24]:
np.std(b)

np.float64(29.46351583623548)

In [25]:
#media de las columnas de un array
np.mean(b, axis=0)

array([36.66666667,  5.        ,  6.        ])

In [ ]:
# practicar axis, min-max,std, mean, y analizar la funcion de reduccion y asi aprender como usarla