In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
c = np.array([1,2,3,4,5])

array([1., 1., 1., 1., 1.])

In [3]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a + c)
print(a - c)
print(a * c)
print(a / c)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
