In [1]:
import numpy as np

In [8]:
#Metodo np.linalg.solve
a = np.array([[3,1],[1,2]])
print (a)
b= np.array([9,8])
print (b)

X=np.linalg.solve(a,b)
print ("Solucion del sistema : ",X)


[[3 1]
 [1 2]]
[9 8]
Solucion del sistema :  [2. 3.]


In [13]:
#comprobrar la solución de un sistema de ecuaciones lineales, se utiliza el np.dot para multiplicar matrices

print ("Verificación de Ax : b",np.dot(a,X))

Verificación de Ax : b [9. 8.]


In [ ]:
#sistema resuleto con la pseudoinversa ( np.linalg.pinv) casos sobre determinados, gran cantidad de ecuaciones y las variables sean menos, tener mas ecuaciones que variables. matriz rectangular
#metodo que minimice el error de la ecuacion lineal
a = np.array([[1,2],[3,4],[5,6]])
print (a)
b = np.array([1,2,3])
print (b)

#calcular el pseudoinverse de la matriz, 
pinv = np.linalg.pinv(a)
print (pinv)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3]
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [18]:
x= np.dot(pinv,b)
print(x)

[0.  0.5]
